//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PmsMtomClient
{

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "IPMSMtomService")]
    public interface IPMSMtomService
    {

        // CODEGEN: Generating message contract since the wrapper name (RequestMessageWithAttachment) of message RequestMessageWithAttachment does not match the default value (Validate)
        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPMSMtomService/Validate", ReplyAction = "http://tempuri.org/IPMSMtomService/ValidateResponse")]
        ResponseMessageWithAttachment Validate(RequestMessageWithAttachment request);

        // CODEGEN: Generating message contract since the wrapper name (RequestMessageWithAttachment) of message RequestMessageWithAttachment does not match the default value (Import)
        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPMSMtomService/Import", ReplyAction = "http://tempuri.org/IPMSMtomService/ImportResponse")]
        ResponseMessage Import(RequestMessageWithAttachment request);

        // CODEGEN: Generating message contract since the wrapper name (RequestMessageWithAttachment) of message RequestMessageWithAttachment does not match the default value (Sign)
        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPMSMtomService/Sign", ReplyAction = "http://tempuri.org/IPMSMtomService/SignResponse")]
        ResponseMessage Sign(RequestMessageWithAttachment request);

        // CODEGEN: Generating message contract since the wrapper name (RequestMessage) of message RequestMessage does not match the default value (Send)
        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPMSMtomService/Send", ReplyAction = "http://tempuri.org/IPMSMtomService/SendResponse")]
        ResponseMessage Send(RequestMessage request);

        // CODEGEN: Generating message contract since the wrapper name (RequestMessage) of message RequestMessage does not match the default value (Export)
        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPMSMtomService/Export", ReplyAction = "http://tempuri.org/IPMSMtomService/ExportResponse")]
        ResponseMessageWithAttachment Export(RequestMessage request);

        // CODEGEN: Generating message contract since the wrapper name (RequestMessage) of message RequestMessage does not match the default value (Remove)
        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPMSMtomService/Remove", ReplyAction = "http://tempuri.org/IPMSMtomService/RemoveResponse")]
        ResponseMessage Remove(RequestMessage request);

        // CODEGEN: Generating message contract since the wrapper name (RequestMessage) of message RequestMessage does not match the default value (Information)
        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPMSMtomService/Information", ReplyAction = "http://tempuri.org/IPMSMtomService/InformationResponse")]
        ResponseMessageWithAttachment Information(RequestMessage request);
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "RequestMessageWithAttachment", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class RequestMessageWithAttachment
    {

        [System.ServiceModel.MessageHeaderAttribute(Namespace = "http://tempuri.org/")]
        public string Meta;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        public System.IO.Stream Attachment;

        public RequestMessageWithAttachment()
        {
        }

        public RequestMessageWithAttachment(string Meta, System.IO.Stream Attachment)
        {
            this.Meta = Meta;
            this.Attachment = Attachment;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "ResponseMessageWithAttachment", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class ResponseMessageWithAttachment
    {

        [System.ServiceModel.MessageHeaderAttribute(Namespace = "http://tempuri.org/")]
        public string PMSResponse;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        public System.IO.Stream Attachment;

        public ResponseMessageWithAttachment()
        {
        }

        public ResponseMessageWithAttachment(string PMSResponse, System.IO.Stream Attachment)
        {
            this.PMSResponse = PMSResponse;
            this.Attachment = Attachment;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "ResponseMessage", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class ResponseMessage
    {

        [System.ServiceModel.MessageHeaderAttribute(Namespace = "http://tempuri.org/")]
        public string PMSResponse;

        public ResponseMessage()
        {
        }

        public ResponseMessage(string PMSResponse)
        {
            this.PMSResponse = PMSResponse;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "RequestMessage", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class RequestMessage
    {

        [System.ServiceModel.MessageHeaderAttribute(Namespace = "http://tempuri.org/")]
        public string Meta;

        public RequestMessage()
        {
        }

        public RequestMessage(string Meta)
        {
            this.Meta = Meta;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IPMSMtomServiceChannel : IPMSMtomService, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class PMSMtomServiceClient : System.ServiceModel.ClientBase<IPMSMtomService>, IPMSMtomService
    {

        public PMSMtomServiceClient()
        {
        }

        public PMSMtomServiceClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
        {
        }

        public PMSMtomServiceClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public PMSMtomServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public PMSMtomServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ResponseMessageWithAttachment IPMSMtomService.Validate(RequestMessageWithAttachment request)
        {
            return base.Channel.Validate(request);
        }

        public string Validate(string Meta, ref System.IO.Stream Attachment)
        {
            RequestMessageWithAttachment inValue = new RequestMessageWithAttachment();
            inValue.Meta = Meta;
            inValue.Attachment = Attachment;
            ResponseMessageWithAttachment retVal = ((IPMSMtomService)(this)).Validate(inValue);
            Attachment = retVal.Attachment;
            return retVal.PMSResponse;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ResponseMessage IPMSMtomService.Import(RequestMessageWithAttachment request)
        {
            return base.Channel.Import(request);
        }

        public string Import(string Meta, System.IO.Stream Attachment)
        {
            RequestMessageWithAttachment inValue = new RequestMessageWithAttachment();
            inValue.Meta = Meta;
            inValue.Attachment = Attachment;
            ResponseMessage retVal = ((IPMSMtomService)(this)).Import(inValue);
            return retVal.PMSResponse;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ResponseMessage IPMSMtomService.Sign(RequestMessageWithAttachment request)
        {
            return base.Channel.Sign(request);
        }

        public string Sign(string Meta, System.IO.Stream Attachment)
        {
            RequestMessageWithAttachment inValue = new RequestMessageWithAttachment();
            inValue.Meta = Meta;
            inValue.Attachment = Attachment;
            ResponseMessage retVal = ((IPMSMtomService)(this)).Sign(inValue);
            return retVal.PMSResponse;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ResponseMessage IPMSMtomService.Send(RequestMessage request)
        {
            return base.Channel.Send(request);
        }

        public string Send(string Meta)
        {
            RequestMessage inValue = new RequestMessage();
            inValue.Meta = Meta;
            ResponseMessage retVal = ((IPMSMtomService)(this)).Send(inValue);
            return retVal.PMSResponse;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ResponseMessageWithAttachment IPMSMtomService.Export(RequestMessage request)
        {
            return base.Channel.Export(request);
        }

        public string Export(string Meta, out System.IO.Stream Attachment)
        {
            RequestMessage inValue = new RequestMessage();
            inValue.Meta = Meta;
            ResponseMessageWithAttachment retVal = ((IPMSMtomService)(this)).Export(inValue);
            Attachment = retVal.Attachment;
            return retVal.PMSResponse;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ResponseMessage IPMSMtomService.Remove(RequestMessage request)
        {
            return base.Channel.Remove(request);
        }

        public string Remove(string Meta)
        {
            RequestMessage inValue = new RequestMessage();
            inValue.Meta = Meta;
            ResponseMessage retVal = ((IPMSMtomService)(this)).Remove(inValue);
            return retVal.PMSResponse;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ResponseMessageWithAttachment IPMSMtomService.Information(RequestMessage request)
        {
            return base.Channel.Information(request);
        }

        public string Information(string Meta, out System.IO.Stream Attachment)
        {
            RequestMessage inValue = new RequestMessage();
            inValue.Meta = Meta;
            ResponseMessageWithAttachment retVal = ((IPMSMtomService)(this)).Information(inValue);
            Attachment = retVal.Attachment;
            return retVal.PMSResponse;
        }
    }
}