SELECT DIARY_TEXT.DIARY_TEXT
    FROM DIARY_TEXT ,DIARY_FIELD
   WHERE ( DIARY_FIELD.FIELD_NUMBER = DIARY_TEXT.FIELD_NUMBER ) and  
    DIARY_TEXT.CASE_ID = @Case_Id and     
    DIARY_FIELD.DIARY_FIELD_TYPE = 4